change main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,12 @@ jobs:
           SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
           SSH_USER: ${{ secrets.DEV_SSH_USER }}
           SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
-      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh ayumi_otake
+      - run: |
+          if [ $? -ne 0 ]; then
+            echo "Failed to SSH into staging server. Exiting..."
+            exit 1
+          fi
+          ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh ayumi_otake
 
   deploy_to_production:
     runs-on: ubuntu-latest
@@ -27,6 +32,9 @@ jobs:
           SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
           SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
           SSH_KEY: ${{ secrets.PRODUCTION_SSHE_SSH_KEY }}
-      - run: ssh ${{ steps.ssh_production.outputs.SERVER }} bash /app/deploy.sh ayumi_otake
-
-
+      - run: |
+          if [ $? -ne 0 ]; then
+            echo "Failed to SSH into production server. Exiting..."
+            exit 1
+          fi
+          ssh ${{ steps.ssh_production.outputs.SERVER }} bash /app/deploy.sh ayumi_otake
